<?xml version="1.0" encoding="utf-8"?><Database Name="new2table" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-QC3NNVP\SQLEXPRESS;Initial Catalog=new2table;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="new2tableConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblDokumanlar" Member="tblDokumanlars">
    <Type Name="tblDokumanlar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FileLocation" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OgretmenID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>